(() => {
  const LS={players:"p247_players_v4",research:"p247_research_v4",draft:"p247_draft_v4",slot:"p247_slot_v4"};
  const clone=x=>JSON.parse(JSON.stringify(x));
  const canonicalId=name=>String(name||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-zA-Z0-9]/g,"").toLowerCase();
  const safeParse=(value,fallback)=>{try{return value?JSON.parse(value):fallback;}catch{return fallback;}};
  const storedPlayers=safeParse(localStorage.getItem(LS.players),null);
  const storedResearch=safeParse(localStorage.getItem(LS.research),null);
  let players=Array.isArray(storedPlayers)&&storedPlayers.length?storedPlayers:clone(window.PLAYER_DATA||[]);
  let research=storedResearch&&typeof storedResearch==="object"&&!Array.isArray(storedResearch)&&Object.keys(storedResearch).length?storedResearch:clone(window.RESEARCH_DATA||{});
  let draft=safeParse(localStorage.getItem(LS.draft),[]);
  if(!Array.isArray(draft)) draft=[];
  let draftSlot=Number(localStorage.getItem(LS.slot)||1);
  const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
  const save=()=>{localStorage.setItem(LS.players,JSON.stringify(players));localStorage.setItem(LS.research,JSON.stringify(research));localStorage.setItem(LS.draft,JSON.stringify(draft));localStorage.setItem(LS.slot,String(draftSlot));};
  const getResearch=p=>research[p.name]||{};
  const avg=arr=>{const v=arr.filter(x=>Number.isFinite(Number(x))).map(Number);return v.length?v.reduce((a,b)=>a+b,0)/v.length:5;};
  const evidenceConfidence=p=>Math.round(avg([getResearch(p).confidence,getResearch(p).roleSecurity,getResearch(p).projectionEdge])*10);

  function footballScore(p){
    const r=getResearch(p);
    const evidence=avg([r.opportunity,r.skills,r.offense,r.roleSecurity,r.upside,r.health,r.projectionEdge])*10;
    const base=Number.isFinite(+p.baseProjection)?+p.baseProjection:evidence;
    let score=evidence*.72+base*.28;
    if(p.pos==="QB") score+=8+((r.opportunity||5)-5)*1.35;
    if(["WR","TE","RB"].includes(p.pos)&&(r.opportunity||0)>=8) score+=2;
    if(Number.isFinite(+r.health)&&+r.health<6) score-=(6-+r.health)*3.2;
    return Math.max(0,Math.min(110,score));
  }
  function consensusSignal(p){const ranks=[p.fpDraftEcr,p.fpRosEcr,p.espnRank].filter(Number.isFinite);if(!ranks.length)return 50;const mean=ranks.reduce((a,b)=>a+b,0)/ranks.length;return Math.max(0,100-mean*.35);}
  function rawValue(p){const f=footballScore(p);const custom=Number.isFinite(+p.customRank)?Math.max(0,100-(+p.customRank*.30)):f;return f*.60+custom*.18+consensusSignal(p)*.22;}
  const draftedRecord=p=>draft.find(d=>d.playerId===canonicalId(p.name));
  const isDrafted=p=>!!draftedRecord(p);
  function pickToTeam(pick){const round=Math.ceil(pick/12),slot=((pick-1)%12)+1;return round%2===1?slot:13-slot;}
  const teamRoster=slot=>draft.filter(d=>d.teamSlot===slot).map(d=>players.find(p=>canonicalId(p.name)===d.playerId)).filter(Boolean);
  function positionCounts(slot){const c={QB:0,RB:0,WR:0,TE:0,K:0,"D/ST":0};teamRoster(slot).forEach(p=>c[p.pos]=(c[p.pos]||0)+1);return c;}
  function nextUserPick(current){for(let p=Math.max(1,current);p<=216;p++)if(pickToTeam(p)===draftSlot)return p;return null;}
  function followingUserPick(current){const first=nextUserPick(current);if(!first)return null;for(let p=first+1;p<=216;p++)if(pickToTeam(p)===draftSlot)return p;return null;}
  function makeBackProbability(p,current){const adp=Number(p.espnAdp);if(!Number.isFinite(adp)||adp>=169.5)return .82;const next=followingUserPick(current)||current+24;const x=(next-adp)/7.5;const draftedByThen=1/(1+Math.exp(-x));return Math.max(.03,Math.min(.97,1-draftedByThen));}
  function rosterNeedBonus(p){const c=positionCounts(draftSlot);if(p.pos==="QB"){if(c.QB===0)return 10;if(c.QB===1)return 8;if(c.QB>=2)return -5;}if(p.pos==="RB")return c.RB<2?5:c.RB<4?2:0;if(p.pos==="WR")return c.WR<2?5:c.WR<5?2:0;if(p.pos==="TE")return c.TE===0?4:-2;if(p.pos==="K"||p.pos==="D/ST")return draft.length<150?-16:0;return 0;}
  function scarcityBonus(p){const a=players.filter(x=>!isDrafted(x)&&x.pos===p.pos).sort((x,y)=>rawValue(y)-rawValue(x));const i=a.findIndex(x=>canonicalId(x.name)===canonicalId(p.name));if(i<0)return 0;const n=a[i+1];if(!n)return 5;return Math.max(0,Math.min(8,(rawValue(p)-rawValue(n))*1.8));}
  function opponentDemandBonus(p){if(p.pos!=="QB")return 0;const hungry=Array.from({length:12},(_,i)=>i+1).filter(s=>s!==draftSlot).filter(s=>positionCounts(s).QB<2).length;return hungry>=8?5:hungry>=5?2:hungry<=2?-3:0;}
  function sleeperScore(p){const r=getResearch(p),adp=Number.isFinite(+p.espnAdp)?+p.espnAdp:180;const cheap=Math.max(0,Math.min(35,(adp-70)*.24)),up=(+r.upside||5)*3.2,opp=(+r.opportunity||5)*2.6,conf=(+r.confidence||5)*1.3,skill=(+r.skills||5)*1.6,health=Math.max(0,7-(+r.health||7))*3,early=adp<85?(85-adp)*.20:0;return Math.max(0,Math.min(100,cheap+up+opp+conf+skill-health-early));}
  function draftNowScore(p,current){const back=makeBackProbability(p,current),urgency=(1-back)*18,evidence=evidenceConfidence(p),weak=evidence<55?(55-evidence)*.20:0;return rawValue(p)+rosterNeedBonus(p)+scarcityBonus(p)+opponentDemandBonus(p)+urgency-weak;}
  function reasonsFor(p,current){const r=getResearch(p),out=[];if((r.opportunity||0)>=8)out.push("Strong projected opportunity");if((r.skills||0)>=9)out.push("High-end skill profile");if((r.offense||0)>=9)out.push("Strong offensive environment");if((r.upside||0)>=9)out.push("Elite ceiling");if((r.health||10)<=5)out.push("Health risk");if(p.pos==="QB")out.push("Custom QB scoring boost");const back=makeBackProbability(p,current);if(back<.30)out.push("Unlikely to make it back");else if(back>.68)out.push("May be safe to wait");if(Number.isFinite(+p.espnAdp)&&Number.isFinite(+p.fpDraftEcr)&&(+p.espnAdp-+p.fpDraftEcr)>=20)out.push("ESPN market discount");if(evidenceConfidence(p)<55)out.push("Evidence still uncertain");return out.slice(0,5);}
  const sortedAvailable=current=>players.filter(p=>!isDrafted(p)).sort((a,b)=>draftNowScore(b,current)-draftNowScore(a,current));
  const bestRawAvailable=()=>players.filter(p=>!isDrafted(p)).sort((a,b)=>rawValue(b)-rawValue(a))[0];
  const pill=(t,type="")=>`<span class="pill ${type}">${t}</span>`, fmtRank=v=>Number.isFinite(+v)?`#${v}`:"—", fmtPct=v=>`${Math.round(v*100)}%`;

  function render(){const current=Math.max(1,Number($("#currentPick").value||1));renderDecision(current);renderBoard(current);renderSleepers(current);renderRosters();}
  function renderDecision(current){const bp=sortedAvailable(current)[0],br=bestRawAvailable();if(bp){$("#bestPickName").textContent=bp.name;$("#bestPickMeta").innerHTML=`${bp.team} ${bp.pos} • Football ${footballScore(bp).toFixed(0)} • Make-back ${fmtPct(makeBackProbability(bp,current))}`;$("#bestPickReasons").innerHTML=reasonsFor(bp,current).map(x=>`<span class="reason">${x}</span>`).join("");}if(br){$("#bestPlayerName").textContent=br.name;$("#bestPlayerMeta").textContent=`${br.team} ${br.pos} • Raw value ${rawValue(br).toFixed(1)}`;}const next=nextUserPick(current),after=followingUserPick(current);$("#nextTurnLabel").textContent=next?`Pick ${next}`:"—";$("#nextTurnMeta").textContent=after?`Following pick: ${after} • ${Math.max(0,after-current)} picks away`:"";}
  function renderBoard(current){const q=$("#search").value.trim().toLowerCase(),pf=$("#positionFilter").value;const rows=players.filter(p=>pf==="ALL"||p.pos===pf).filter(p=>!q||p.name.toLowerCase().includes(q)).sort((a,b)=>isDrafted(a)!==isDrafted(b)?(isDrafted(a)?1:-1):draftNowScore(b,current)-draftNowScore(a,current));$("#playerTable tbody").innerHTML=rows.map(p=>{const d=draftedRecord(p),back=makeBackProbability(p,current),ev=evidenceConfidence(p),sl=sleeperScore(p),note=getResearch(p).notes||"Add research evidence before relying on this recommendation.";return `<tr class="${d?"drafted":""}" title="${note.replace(/"/g,'&quot;')}"><td>${d?`#${d.pick}`:""}</td><td><div class="name">${p.name}</div><div class="small">${p.team}</div></td><td>${pill(p.pos)}</td><td><strong>${rawValue(p).toFixed(1)}</strong></td><td>${footballScore(p).toFixed(0)}</td><td>${pill(Math.round(sl),sl>=75?"good":sl>=60?"warn":"")}</td><td>${fmtRank(p.espnRank)}<div class="small">ADP ${Number.isFinite(+p.espnAdp)?(+p.espnAdp).toFixed(1):"—"}</div></td><td>${fmtRank(p.fpDraftEcr)}</td><td>${fmtRank(p.fpRosEcr)}</td><td>${pill(fmtPct(back),back<.30?"bad":back>.68?"good":"warn")}</td><td>${pill(`${ev}%`,ev>=75?"good":ev<55?"bad":"warn")}</td><td>${d?`<button class="ghost undo" data-id="${canonicalId(p.name)}">Undo</button>`:`<button class="draft" data-id="${canonicalId(p.name)}">Draft</button>`}</td></tr>`;}).join("");$$('.draft').forEach(b=>b.onclick=()=>draftPlayer(b.dataset.id));$$('.undo').forEach(b=>b.onclick=()=>undoPlayer(b.dataset.id));}
  function renderSleepers(current){const s=players.filter(p=>!isDrafted(p)&&sleeperScore(p)>=55).sort((a,b)=>sleeperScore(b)-sleeperScore(a)).slice(0,24);$("#sleeperCards").innerHTML=s.map(p=>{const r=getResearch(p);return `<article class="sleeper-card"><div class="eyebrow">${p.pos} • ${p.team}</div><h3>${p.name}</h3><div class="score">${Math.round(sleeperScore(p))}</div><div class="small">Sleeper score</div><p class="note">${r.notes||"No football thesis entered yet."}</p><div class="reasons">${pill(`ESPN ADP ${Number.isFinite(+p.espnAdp)?(+p.espnAdp).toFixed(1):"—"}`)}${pill(`Make back ${fmtPct(makeBackProbability(p,current))}`)}${pill(`Evidence ${evidenceConfidence(p)}%`,evidenceConfidence(p)>=75?"good":"warn")}</div></article>`;}).join("");}
  function renderRosters(){$("#rosterGrid").innerHTML=Array.from({length:12},(_,i)=>i+1).map(slot=>{const r=teamRoster(slot),c=positionCounts(slot);return `<article class="roster ${slot===draftSlot?"me":""}"><h3>${slot===draftSlot?"Your Team":"Team "+slot}</h3><div class="small">QB ${c.QB} • RB ${c.RB} • WR ${c.WR} • TE ${c.TE}</div><ul>${r.map(p=>`<li>${p.name} (${p.pos})</li>`).join("")||"<li>—</li>"}</ul></article>`;}).join("");}
  function draftPlayer(id){const current=Math.max(1,Number($("#currentPick").value||1)),p=players.find(x=>canonicalId(x.name)===id);if(!p||isDrafted(p))return;draft.push({playerId:id,pick:current,teamSlot:pickToTeam(current)});$("#currentPick").value=current+1;save();render();toast(`${p.name} drafted at pick ${current}`);}
  function undoPlayer(id){draft=draft.filter(d=>d.playerId!==id);save();render();}
  function toast(msg){const t=$("#toast");t.textContent=msg;t.classList.remove("hidden");setTimeout(()=>t.classList.add("hidden"),1800);}
  function downloadJson(filename,obj){const blob=new Blob([JSON.stringify(obj,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=filename;a.click();URL.revokeObjectURL(a.href);}
  function setup(){$("#draftSlot").innerHTML=Array.from({length:12},(_,i)=>`<option value="${i+1}">${i+1}</option>`).join("");$("#draftSlot").value=draftSlot;$("#draftSlot").onchange=e=>{draftSlot=+e.target.value;save();render();};$("#currentPick").oninput=render;$("#positionFilter").onchange=render;$("#search").oninput=render;$$('.tab').forEach(btn=>btn.onclick=()=>{$$('.tab').forEach(x=>x.classList.remove('active'));btn.classList.add('active');$$('.tab-pane').forEach(x=>x.classList.add('hidden'));$('#'+btn.dataset.tab+'Tab').classList.remove('hidden');});$("#resetBtn").onclick=()=>{if(!confirm("Reset all drafted-player history? Player/research data will remain."))return;draft=[];$("#currentPick").value=1;save();render();};$("#importPlayersBtn").onclick=()=>{try{const v=JSON.parse($("#playerImport").value);if(!Array.isArray(v))throw new Error("Player import must be a JSON array.");players=v;draft=[];save();render();toast("Player data imported");}catch(e){alert(e.message);}};$("#exportPlayersBtn").onclick=()=>downloadJson("players.json",players);$("#importResearchBtn").onclick=()=>{try{const v=JSON.parse($("#researchImport").value);if(!v||Array.isArray(v)||typeof v!=="object")throw new Error("Research import must be a JSON object keyed by player name.");research=v;save();render();toast("Research imported");}catch(e){alert(e.message);}};$("#exportResearchBtn").onclick=()=>downloadJson("research.json",research);render();}
  setup();
})();
